version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0811
      - POSTGRES_DB=amadeus_flight
    ports:
      - "5433:5432"